export const ADMIN_ORDER_REQUEST="ADMIN_ORDER_REQUEST"
export const ADMIN_ORDER_SUCCESS="ADMIN_ORDER_SUCCESS"
export const ADMIN_ORDER_FAILES="ADMIN_ORDER_FAILES"

export const DELETE_ORDER_REQUEST="DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILES="DELETE_ORDER_FAILES"
export const DELETE_ORDER_RESET="DELETE_ORDER_RESET"

export const UPDATE_ORDER_REQUEST="UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER_SUCCESS="UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAILES="UPDATE_ORDER_FAILES"
export const UPDATE_ORDER_RESET="UPDATE_ORDER_RESET"