export const ADMIN_PRODUCT_REQUEST="ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS="ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAILES="ADMIN_PRODUCT_FAILES"

export const CREATE_PRODUCT_REQUEST="CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILES="CREATE_PRODUCT_FAILES"
export const CREATE_PRODUCT_RESET="CREATE_PRODUCT_RESET"

export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILES="DELETE_PRODUCT_FAILES"
export const DELETE_PRODUCT_RESET="DELETE_PRODUCT_RESET"

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILES="UPDATE_PRODUCT_FAILES"
export const UPDATE_PRODUCT_RESET="UPDATE_PRODUCT_RESET"