export const ADMIN_USER_REQUEST="ADMIN_USER_REQUEST"
export const ADMIN_USER_SUCCESS="ADMIN_USER_SUCCESS"
export const ADMIN_USER_FAILES="ADMIN_USER_FAILES"

export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"
export const DELETE_USER_FAILES="DELETE_USER_FAILES"
export const DELETE_USER_RESET="DELETE_USER_RESET"

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILES="UPDATE_USER_FAILES"
export const UPDATE_USER_RESET="UPDATE_USER_RESET"

export const ADMIN_USERDETAILS_REQUEST="ADMIN_USERDETAILS_REQUEST"
export const ADMIN_USERDETAILS_SUCCESS="ADMIN_USERDETAILS_SUCCESS"
export const ADMIN_USERDETAILS_FAILES="ADMIN_USERDETAILS_FAILES"