export const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILES="ADD_TO_CART_FAILES"
export const RESET_CART_STATE="RESET_CART_STATE"
export const CART_DELETE="CART_DELETE"

export const ADD_ADDERSS_REQUEST="ADD_ADDERSS_REQUEST"
export const ADD_ADDERSS_SUCCESS="ADD_ADDERSS_SUCCESS"
export const ADD_ADDERSS_FAILES="ADD_ADDERSS_FAILES"

export const DELETE_ADDRESS="DELETE_ADDRESS"