export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILES="CREATE_ORDER_FAILES"

export const CLEARE_ERRORS="CLEARE_ERRORS"

export const MY_ORDERS_REQUEST="MY_ORDERS_REQUEST"
export const MY_ORDERS_SUCCESS="MY_ORDERS_SUCCESS"
export const MY_ORDERS_FAILES="MY_ORDERS_FAILES"

export const SINGLE_ORDER_REQUEST="SINGLE_ORDER_REQUEST"
export const SINGLE_ORDER_SUCCESS="SINGLE_ORDER_SUCCESS"
export const SINGLE_ORDER_FAILES="SINGLE_ORDER_FAILES"

export const PAYMENT_REQUEST="PAYMENT_REQUEST"
export const PAYMENT_SUCCESS="PAYMENT_SUCCESS"
export const PAYMENT_FAILES="PAYMENT_FAILES"

export const CANCEL_ORDER_REQUEST="CANCEL_ORDER_REQUEST"
export const CANCEL_ORDER_SUCCESS="CANCEL_ORDER_SUCCESS"
export const CANCEL_ORDER_FAILES="CANCEL_ORDER_FAILES"
export const CANCEL_ORDER_RESET="CANCEL_ORDER_RESET"

