export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAILES="ALL_PRODUCT_FAILES"
export const ALL_PRODUCT_RESET="ALL_PRODUCT_RESET"

export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAILES="PRODUCT_DETAILS_FAILES"
export const PRODUCT_DETAILS_RESET="PRODUCT_DETAILS_RESET"

export const REVIEW_REQUEST="REVIEW_REQUEST"
export const REVIEW_SUCCESS="REVIEW_SUCCESS"
export const REVIEW_FAILES="REVIEW_FAILES"
export const REVIEW_RESET="REVIEW_RESET"

export const CLEARE_ERRORS="CLEARE_ERRORS"