export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILES="LOGIN_FAILES"

export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAILES="REGISTER_FAILES"

export const AUTH_USER_REQUEST="AUTH_USER_REQUEST"
export const AUTH_USER_SUCCESS="AUTH_USER_SUCCESS"
export const AUTH_USER_FAILES="AUTH_USER_FAILES"

export const LOGOUT_USER_SUCCESS="LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAILES="LOGOUT_USER_FAILES"

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_RESET="UPDATE_PROFILE_RESET"
export const UPDATE_PROFILE_FAILES="UPDATE_PROFILE_FAILES"

export const CHANGE_PASSWORD_REQUEST="CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_RESET="CHANGE_PASSWORD_RESET"
export const CHANGE_PASSWORD_FAILES="CHANGE_PASSWORD_FAILES"

export const DELETE_ACCOUNT_REQUEST="DELETE_ACCOUNT_REQUEST"
export const DELETE_ACCOUNT_SUCCESS="DELETE_ACCOUNT_SUCCESS"
export const DELETE_ACCOUNT_RESET="DELETE_ACCOUNT_RESET"
export const DELETE_ACCOUNT_FAILES="DELETE_ACCOUNT_FAILES"

export const FORGETE_PASSWORD_REQUEST="FORGETE_PASSWORD_REQUEST"
export const FORGETE_PASSWORD_SUCCESS="FORGETE_PASSWORD_SUCCESS"
export const FORGETE_PASSWORD_FAILES="FORGETE_PASSWORD_FAILES"

export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILES="RESET_PASSWORD_FAILES"

export const VERIFY_EMAIL_REQUEST="VERIFY_EMAIL_REQUEST"
export const VERIFY_EMAIL_SUCCESS="VERIFY_EMAIL_SUCCESS"
export const VERIFY_EMAIL_FAILES="VERIFY_EMAIL_FAILES"

export const REQUEST_EMAIL_REQUEST="REQUEST_EMAIL_REQUEST"
export const REQUEST_EMAIL_SUCCESS="REQUEST_EMAIL_SUCCESS"
export const REQUEST_EMAIL_FAILES="REQUEST_EMAIL_FAILES"

export const CONFIRM_EMAIL_REQUEST="CONFIRM_EMAIL_REQUEST"
export const CONFIRM_EMAIL_SUCCESS="CONFIRM_EMAIL_SUCCESS"
export const CONFIRM_EMAIL_FAILES="CONFIRM_EMAIL_FAILES"

export const RESET_STATE="RESET_STATE"



export const CLEARE_ERRORS="CLEARE_ERRORS"
